movies/urls.py
from django.urls import path
from . import views

app_name = 'movie'

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:movie_id>', views.detail, name="detail")
]

vidly/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import MovieResource
from . import views

movie_resource = MovieResource()


urlpatterns = [
    path('', views.home),
    path('admin/', admin.site.urls),
    path('movies/', include('movies.urls')),
    path('api/', include(movie_resource.urls))


]

api/models.py
from django.db import models
from tastypie.resources import ModelResource
from movies.models import Movie

# Create your models here.

class MovieResource(ModelResource):
    class Meta:
        queryset = Movie.objects.all()
        resource_name = 'movies'

movies/models.py
from django.db import models

# Create your models here.

class Genre(models.Model):

    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

class Movie(models.Model):
    title = models.CharField(max_length=255)
    release_year = models.IntegerField()
    stock = models.IntegerField()
    daily_rate = models.FloatField()
    genre = models.ForeignKey(Genre, on_delete=models.CASCADE)
    images_url = models.CharField(max_length=2083)
    description = models.TextField(max_length=1000, blank=True)
    duration = models.CharField(max_length=10)

api/views.py
from django.shortcuts import render

# Create your views here.

movies/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse
from .models import Movie

# Create your views here.


def index(request):
    movies = Movie.objects.all()

    return render(request, 'movies/index.html', {'movies': movies})


def detail(request, movie_id):
    movie = get_object_or_404(Movie, pk=movie_id)
    return render(request,  'movies/detail.html', {'movie': movie})

vidly/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'home.html')

movies/templates/movies/detail.html
{% extends 'base.html' %}

{% block content %}

<div class="container">

    <div class="card mb-3" style="max-width: 100%;margin-top:4rem; border:none">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="{{movie.images_url}}" class="img-fluid rounded-start"  alt="..." >
    </div>
    <div class="col-md-8">
      <div class="card-body">

        <h5 class="card-title">{{ movie.title}}</h5>

           <p  class="card-text">{{movie.genre}} {{movie.duration}}</p>
            <p  class="card-text">{{movie.release_year}}</p>
        <p class="card-text">
            {{movie.description}}
        </p>
           <a href="#"  style= "display:inline-block; "class="btn btn-warning">Watch Now </a>
          <a href="{% url 'movie:index' %}"  style= "display:inline-block; "class="btn btn-dark"> back </a>


      </div>

    </div>
  </div>
</div>


</div>



{% endblock  %}

movies/templates/movies/index.html
{% extends 'base.html'%}



{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">

    <div class="container">
        <h1 class="movielist">Movies List</h1>

        <div class="row">
            {% for movie in movies %}
            <div class="col">
                <div class="card" style="width: 18rem; height: 24rem;margin-top:3rem;">
                    <img src="{{movie.images_url}}" class="card-img-top" alt="...">
                    <div class="card-body">
                        <h5 class="card-title">{{ movie.title}}</h5>
                        <p  class="card-text">{{movie.genre}}</p>
                          <p  class="card-text">{{movie.release_year}}</p>
                        <a href="#" class="btn btn-warning">Watch Now</a>
                        <a href="{% url 'movie:detail' movie.id %}" class="btn btn-outline-secondary">Detail</a>
                    </div>


                </div>

            </div>
            {% endfor %}
        </div>

    </div>

{% endblock%}

templates/base.html
{% load static %}

<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <link rel="shortcut icon" type="image/jpg" sizes="52x52" href="{% static 'images/movie-film.png' %}"/>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <title>V watch</title>
  </head>
  <body>

  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-md">
    <a class="navbar-brand" href="{% url 'movie:index' %}"><h1>V-Watch</h1></a>
  </div>
</nav>


    {% block content  %}

    {% endblock   %}


    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

templates/home.html
{% extends 'base.html' %}



{% block content %}

{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">



<div class="container">

    <div class="hero">
    <div class="herotext">
        <h1 class="hero-text">Watch your's favorite movie <br> on V-watch all day! </h1>
 <a href="{% url 'movie:index' %}"><button type="button" class="btn btn-outline-secondary btn-all">Watch Now &#10230;</button></a>
    </div>
    <div class="heroimg">
        <img class="hero-img" src="{%static 'images/watching-a-movie.png' %}" alt="">
    </div>

</div>

</div>



{% endblock %}